version: "3.8"

services:
  baileys-server-pro:
    # Build from repository instead of pulling pre-built image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baileys-server-pro
    restart: unless-stopped
    # Run as node user (UID 1000, GID 1000) for proper permissions
    user: "1000:1000"
    ports:
      # Bind to localhost only - not accessible from outside VPS
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - API_BASE_URL=${API_BASE_URL:-}
    volumes:
      - wasap_sessions:/usr/src/app/sessions
      - wasap_uploads:/usr/src/app/uploads
    networks:
      - wasap-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  wasap_sessions:
    driver: local
  wasap_uploads:
    driver: local

networks:
  wasap-network:
    driver: bridge